### ISSUE TITLE
Add a 'onKeyPress|onKeyDown|onKeyUp' attribute to this <div> tag.

### ISSUE THREAD

**Issue by NaMax66** [VirtoCommerce/vc-frontend#1095]
https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&id=VirtoCommerce_vc-theme-b2b-vue

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8578 has been created

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8640 has been created
