### ISSUE TITLE
Use 'String#startsWith' method instead.

### ISSUE THREAD

**Issue by NaMax66** [VirtoCommerce/vc-frontend#1096]
https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&sinceLeakPeriod=true&id=VirtoCommerce_vc-theme-b2b-vue&open=AYsj_wW9YvBRTHtM-ZCo

also fix others the same

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8579 has been created

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8636 has been created
