### ISSUE TITLE
remove Product type from useGoogleAnalytics

### ISSUE THREAD

**Issue by NaMax66** [VirtoCommerce/vc-frontend#1098]
1. refactor useGoogleAnalytics
2. remove as Product from product.vue ga.viewItem

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8581 has been created

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8638 has been created

**Comment by NaMax66** [comment]
https://virtocommerce.atlassian.net/browse/VCST-1935
