### ISSUE TITLE
remove Product type from ProductSidebar

### ISSUE THREAD

**Issue by NaMax66** [VirtoCommerce/vc-frontend#1099]
1. Refactor ProductSidebar
2. Remove computed `sideBarProduct` from product.vue

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8580 has been created

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8639 has been created

**Comment by NaMax66** [comment]
https://virtocommerce.atlassian.net/browse/VCST-1934
