### ISSUE TITLE
Store ID routes are not handled

### ISSUE THREAD

**Issue by jewells77** [VirtoCommerce/vc-frontend#835]
I'm using Vue theme, and I want to do white labeling, but with the store ID, the routes are not working.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8468 has been created

**Comment by Dan-BV** [comment]
HI, @jewells77 !
In the current version of the theme, getting a store ID is not supported. 
To configure domains, you can refer to the following documentation https://www.virtocommerce.org/t/configuring-multiple-stores-with-multiple-domains-in-virto-commerce-a-comprehensive-guide/588

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8635 has been created
